server:
  port: 8095
spring:
  datasource:
    url: jdbc:mysql://rm-bp1d61y593468858gjo.mysql.rds.aliyuncs.com:3306/homepainter?useSSL=false
    username: qxg
    password: 370105qihs0813!
    driver-class-name: com.mysql.cj.jdbc.Driver
  server:
    tomcat:
      #设定tomcat的basedir目录，如果没有指定则使用临时目录
      basedir: /home/app/tomcat_upload_temp


mybatis:
  type-aliases-package: com.homepainter.pojo
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    cn.itcast: debug







