server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://sh-cynosdbmysql-grp-2qr6s4ri.sql.tencentcdb.com:20461/homepainter?useSSL=false
    username: root
    password: 370105qihs0813QC
    driver-class-name: com.mysql.cj.jdbc.Driver
  server:
    tomcat:
      #设定tomcat的basedir目录，如果没有指定则使用临时目录
      basedir: /home/app/tomcat_upload_temp


mybatis:
  type-aliases-package: com.homepainter.pojo
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    cn.itcast: debug







